#!/bin/bash

OUTPUT_FILE="yegna-ai-complete-code.txt"

# Clear output file
> "$OUTPUT_FILE"

# Function to add file with separator
add_file() {
    local file="$1"
    if [ -f "$file" ]; then
        echo "" >> "$OUTPUT_FILE"
        echo "================================================================" >> "$OUTPUT_FILE"
        echo "FILE: $file" >> "$OUTPUT_FILE"
        echo "================================================================" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
        cat "$file" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
        echo "================================================================" >> "$OUTPUT_FILE"
        echo "END OF FILE: $file" >> "$OUTPUT_FILE"
        echo "================================================================" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
    else
        echo "⚠️  File not found: $file"
    fi
}

# Add all files in order
add_file "turbo.json"
add_file "vercel.json"
add_file "package.json"
add_file ".env.example"
add_file "apps/web/next.config.js"
add_file "apps/web/jsconfig.json"
add_file "apps/web/package.json"
add_file "apps/api/package.json"
add_file "packages/config/src/index.js"
add_file "packages/config/src/levels.config.json"
add_file "packages/config/src/commission.config.json"
add_file "packages/config/src/tasks.config.json"
add_file "packages/config/src/payment.config.json"
add_file "packages/config/src/breadcrumbs.config.json"
add_file "packages/config/src/navigation.config.json"
add_file "packages/utils/src/index.js"
add_file "packages/utils/src/calculators.js"
add_file "packages/utils/src/formatters.js"
add_file "packages/utils/src/validators.js"
add_file "packages/utils/src/constants.js"
add_file "apps/api/utils/database.js"
add_file "database/migrations/001_create_users.sql"
add_file "database/migrations/002_create_wallets.sql"
add_file "database/migrations/003_create_levels.sql"
add_file "database/migrations/004_create_tasks.sql"
add_file "database/migrations/005_create_teams.sql"
add_file "database/migrations/006_create_commissions.sql"
add_file "database/migrations/007_create_transactions.sql"
add_file "database/migrations/008_create_withdrawals.sql"
add_file "database/seeds/levels.sql"
add_file "apps/api/index.js"
add_file "apps/api/middleware/auth.middleware.js"
add_file "apps/api/middleware/validation.middleware.js"
add_file "apps/api/middleware/error.middleware.js"
add_file "apps/api/middleware/rateLimit.middleware.js"
add_file "apps/api/utils/jwt.js"
add_file "apps/api/utils/cloudinary.js"
add_file "apps/api/models/user.model.js"
add_file "apps/api/models/task.model.js"
add_file "apps/api/models/wallet.model.js"
add_file "apps/api/models/commission.model.js"
add_file "apps/api/services/auth.service.js"
add_file "apps/api/services/task.service.js"
add_file "apps/api/services/wallet.service.js"
add_file "apps/api/services/commission.service.js"
add_file "apps/api/controllers/auth.controller.js"
add_file "apps/api/controllers/task.controller.js"
add_file "apps/api/controllers/wallet.controller.js"
add_file "apps/api/routes/auth.routes.js"
add_file "apps/api/routes/task.routes.js"
add_file "apps/api/routes/wallet.routes.js"
add_file "apps/web/src/pages/_app.jsx"
add_file "apps/web/src/pages/_document.jsx"
add_file "apps/web/src/pages/index.jsx"
add_file "apps/web/src/context/ConfigContext.jsx"
add_file "apps/web/src/context/AuthContext.jsx"
add_file "apps/web/src/context/ToastContext.jsx"
add_file "apps/web/src/styles/globals.css"
add_file "apps/web/src/styles/variables.css"
add_file "apps/web/src/middleware.js"
add_file "apps/web/src/components/layout/RootLayout.jsx"
add_file "apps/web/src/components/layout/Header.jsx"
add_file "apps/web/src/components/layout/Footer.jsx"
add_file "apps/web/src/components/navigation/Breadcrumbs.jsx"
add_file "apps/web/src/components/ui/Button.jsx"
add_file "apps/web/src/components/ui/Card.jsx"
add_file "apps/web/src/components/ui/Modal.jsx"
add_file "apps/web/src/components/ui/Toast.jsx"
add_file "apps/web/src/components/ui/Spinner.jsx"
add_file "apps/web/src/components/ui/Badge.jsx"

echo "✅ All files merged into: $OUTPUT_FILE"
